#!/bin/bash
for i in {90..100}
do
     ping 172.19.233.$i -w 1 > /dev/null
     if [ $? -eq 0 ]; then
        host = 172.19.233.$i
        echo host
     else 
        echo "no"
     fi
done
echo "complete"
